services:
    - type: web
      name: sveltekit-poc
      env: node
      buildCommand: npm install && npx prisma generate && npx prisma migrate dev && npm run build
      startCommand: node build/index.js
